export const circleData = [
    { state: 'Andaman And Nicobar', circleCode: '' },
    { state: 'Andhra Pradesh', circleCode: '13' },
    { state: 'Arunachal Pradesh', circleCode: '' },
    { state: 'Assam', circleCode: '24' },
    { state: 'Bihar', circleCode: '17' },
    { state: 'Chandigarh', circleCode: '' },
    { state: 'Chhattisgarh', circleCode: '27' },
    { state: 'Dadra Nager Haveli', circleCode: '' },
    { state: 'Daman And Div', circleCode: '' },
    { state: 'Goa', circleCode: '' },
    { state: 'Gujarat', circleCode: '12' },
    { state: 'Haryana', circleCode: '20' },
    { state: 'Himachal Pradesh', circleCode: '21' },
    { state: 'Jammu And Kashmir', circleCode: '25' },
    { state: 'Jharkhand', circleCode: '22' },
    { state: 'Karnataka', circleCode: '9' },
    { state: 'Kerala', circleCode: '14' },
    { state: 'Lakshadweep', circleCode: '' },
    { state: 'Madhya Pradesh', circleCode: '16' },
    { state: 'Maharashtra', circleCode: '4' },
    { state: 'Manipur', circleCode: '' },
    { state: 'Meghalaya', circleCode: '' },
    { state: 'Mizoram', circleCode: '' },
    { state: 'Nagaland', circleCode: '' },
    { state: 'New Delhi', circleCode: '' },
    { state: 'Orissa', circleCode: '23' },
    { state: 'Pondicherry', circleCode: '' },
    { state: 'Punjab', circleCode: '1' },
    { state: 'Rajasthan', circleCode: '18' },
    { state: 'Sikkim', circleCode: '' },
    { state: 'Tamil Nadu', circleCode: '8' },
    { state: 'Tripura', circleCode: '' },
    { state: 'Uttar Pradesh East', circleCode: '10' },
    { state: 'Uttaranchal', circleCode: '' },
    { state: 'West Bengal', circleCode: '2' },
    { state: 'Uttar Pradesh West', circleCode: '11' },
    { state: 'Mumbai', circleCode: '3' },
    { state: 'Delhi', circleCode: '5' },
    { state: 'CHENNAI', circleCode: '7' },
    { state: 'NORTH EAST', circleCode: '26' },
    { state: 'Kolkata', circleCode: '6' },
  ];