export const RechargeServiceTypes = {
    Mobile: "Mobile",
    DTH: "DTH",
    PostPaid: "PostPaid",
    Electricity: "Electricity",
    Gas: "Gas"
}
export const RechargeMetaData = [
    { "name": "Airtel", "code": "A", "type": "Mobile" },
    { "name": "Vodafone", "code": "V", "type": "Mobile" },
    { "name": "BSNL - TOPUP", "code": "BT", "type": "Mobile" },
    { "name": "RELIANCE - JIO", "code": "RC", "type": "Mobile" },
    { "name": "Idea", "code": "I", "type": "Mobile" },
    { "name": "BSNL - STV", "code": "BR", "type": "Mobile" },
    { "name": "Airtel Digital DTH TV", "code": "ATV", "type": "DTH" },
    { "name": "SUNDIRECT DTH TV", "code": "STV", "type": "DTH" },
    { "name": "TATASKY DTH TV", "code": "TTV", "type": "DTH" },
    { "name": "VIDEOCON DTH TV", "code": "VTV", "type": "DTH" },
    { "name": "DISH TV", "code": "DTV", "type": "DTH" },
    { "name": "Airtel Postpaid", "code": "PAT", "type": "PostPaid" },
    { "name": "Idea Postpaid", "code": "IP", "type": "PostPaid" },
    { "name": "Vodafone Postpaid", "code": "VP", "type": "PostPaid" },
    { "name": "Tata Docomo Postpaid", "code": "DP", "type": "PostPaid" },
    { "name": "BSNL Postpaid", "code": "BP", "type": "PostPaid" },
    { "name": "Bsnl Landline", "code": "LBS", "type": "PostPaid" },
    { "name": "MTNL Delhi Landline", "code": "LMT", "type": "PostPaid" },
    { "name": "Airtel Landline", "code": "LAT", "type": "PostPaid" },
    { "name": "JIO POSTPAID", "code": "JPP", "type": "PostPaid" },
    { "name": "North Bihar Electricity", "code": "NBE", "type": "Electricity" },
    { "name": "JBVNL - JHARKHAND", "code": "JBVNL", "type": "Electricity" },
    { "name": "Assam Power Distribution Company Ltd (RAPDR)", "code": "APDCLR", "type": "Electricity" },
    { "name": "Mangalore Electricity Supply Co. Ltd (MESCOM) - RAPDR", "code": "MESCOMR", "type": "Electricity" },
    { "name": "APDCL (Non-RAPDR) - ASSAM", "code": "APDCLN", "type": "Electricity" },
    { "name": "Mangalore Electricity Supply Co. Ltd (Non) - RAPDR", "code": "MESCOMNR", "type": "Electricity" },
    { "name": "BSES Rajdhani Power Limited - Delhi", "code": "BSES", "type": "Electricity" },
    { "name": "BSES Yamuna Power Limited - Delhi", "code": "BSESY", "type": "Electricity" },
    { "name": "Tata Power Delhi Limited - Delhi", "code": "TPD", "type": "Electricity" },
    { "name": "Tata Power - MUMBAI", "code": "TPDM", "type": "Electricity" },
    { "name": "Hubli Electricity Supply Company Ltd. (HESCOM)", "code": "HESCOM", "type": "Electricity" },
    { "name": "South Bihar Electricity", "code": "SBE", "type": "Electricity" },
    { "name": "BEST Mumbai", "code": "BEST", "type": "Electricity" },
    { "name": "Ajmer Vidyut Vitran Nigam - RAJASTHAN", "code": "AJV", "type": "Electricity" },
    { "name": "Bangalore ElectricitySupply Company", "code": "BESCOM", "type": "Electricity" },
    { "name": "CESC - WEST BENGAL", "code": "CESC", "type": "Electricity" },
    { "name": "Jaipur Vidyut Vitran Nigam - RAJASTHAN", "code": "JVV", "type": "Electricity" },
    { "name": "Jodhpur Vidyut Vitran Nigam - RAJASTHAN", "code": "JDVV", "type": "Electricity" },
    { "name": "MP Madhaya Kshetra Vidyut Vitaran -Urban", "code": "MKV", "type": "Electricity" },
    { "name": "MSEDC - MAHARASHTRA", "code": "MSEDC", "type": "Electricity" },
    { "name": "Noida Power - NOIDA", "code": "NP", "type": "Electricity" },
    { "name": "Paschim Kshetra Vitaran - MADHYA PRADESH", "code": "PKV", "type": "Electricity" },
    { "name": "Southern Power - ANDHRA PRADESH", "code": "SPA", "type": "Electricity" },
    { "name": "Southern Power - TELANGANA", "code": "SPT", "type": "Electricity" },
    { "name": "Torrent Power agra", "code": "TRP", "type": "Electricity" },
    { "name": "Central Power Distribution Company of Andhra Pradesh Ltd", "code": "APCPDCL", "type": "Electricity" },
    { "name": "Department of Power Arunachal Pradesh", "code": "ARPDOP", "type": "Electricity" },
    { "name": "Western Electricity supply co. Of orissa ltd.", "code": "WESCO", "type": "Electricity" },
    { "name": "Paschim Gujarat Vij Company Ltd", "code": "PGVCL", "type": "Electricity" },
    { "name": "BharatpurElectricityServicesLtd", "code": "BHES", "type": "Electricity" },
    { "name": "Muzaffarpur Vidyut Vitran", "code": "MVV", "type": "Electricity" },
    { "name": "Madhya Gujarat Vij Company Ltd", "code": "MGVCL", "type": "Electricity" },
    { "name": "MEPDCL - MEGHALAYA", "code": "MEPDCL", "type": "Electricity" },
    { "name": "KEDL - KOTA", "code": "KEDL", "type": "Electricity" },
    { "name": "Dakshin Gujarat Vij Company Ltd", "code": "DGVCL", "type": "Electricity" },
    { "name": "WBSEDCL - WEST BENGAL", "code": "WBSEDCL", "type": "Electricity" },
    { "name": "SNDL Power - NAGPUR", "code": "SNDL", "type": "Electricity" },
    { "name": "Bikaner Electricity Supply Limited", "code": "BESL", "type": "Electricity" },
    { "name": "India Power - WEST BENGAL", "code": "IPWB", "type": "Electricity" },
    { "name": "BrihanMumbaiElectricSupplyandTransportUndertaking", "code": "BMESTU", "type": "Electricity" },
    { "name": "APEPDCL - ANDHRA PRADESH", "code": "APEPDCL", "type": "Electricity" },
    { "name": "TNEB - TAMIL NADU", "code": "TNEB", "type": "Electricity" },
    { "name": "UPPCL (URBAN) - UTTAR PRADESH", "code": "UPPCLU", "type": "Electricity" },
    { "name": "Uttar Pradesh Power Corporation Limited(Rular)", "code": "UPPCLR", "type": "Electricity" },
    { "name": "DakshinHaryanaBijliVitranNigam", "code": "DHBVN", "type": "Electricity" },
    { "name": "TSNPDCL Telangana northern power", "code": "TSNPDCL", "type": "Electricity" },
    { "name": "DNHPowerDistributionCompanyLimited", "code": "DDCL", "type": "Electricity" },
    { "name": "GulbargaElectricitySupplyCompanyLimited", "code": "GESCL", "type": "Electricity" },
    { "name": "IndiaPowerCorporationLimited", "code": "IPCL", "type": "Electricity" },
    { "name": "JamshedpurUtilitiesandServicesCompanyLimited", "code": "JUSCL", "type": "Electricity" },
    { "name": "Chhattisgarh State Power Distribution Company Ltd. (CSPDCL)", "code": "CSPDCL", "type": "Electricity" },
    { "name": "Goa Electricity", "code": "GOAELC", "type": "Electricity" },
    { "name": "UttarGujarat Vij Company Ltd", "code": "UGVCL", "type": "Electricity" },
    { "name": "Torrent Power Surat", "code": "TORRENTSUR", "type": "Electricity" },
    { "name": "Torrent Power Ahemdabad", "code": "TORRENTAHM", "type": "Electricity" },
    { "name": "Gift Power Company Limited", "code": "GPCL", "type": "Electricity" },
    { "name": "Himachal Pradesh State Electricity Board Ltd", "code": "HPSEBL", "type": "Electricity" },
    { "name": "Jammu & Kashmir power Development department", "code": "JKPDD", "type": "Electricity" },
    { "name": "Chamundeshwari Electricity Supply Corporation Ltd. (Cesc,Mysore)", "code": "CESCOM", "type": "Electricity" },
    { "name": "NorthDelhiPowerLimited", "code": "NDPL", "type": "Electricity" },
    { "name": "MUNICIPALCORPORATIONOFGURUGRAM", "code": "MCG", "type": "Electricity" },
    { "name": "Punjab State Power Corporation Limted", "code": "PSPCL", "type": "Electricity" },
    { "name": "TripuraStateElectricityCorporationLtd", "code": "TSECL", "type": "Electricity" },
    { "name": "UttarHaryanaBijliVitranNigam", "code": "UHBV", "type": "Electricity" },
    { "name": "UttarakhandPowerCorporationLimited", "code": "UKPCL", "type": "Electricity" },
    { "name": "Kerala State Electricity Board Ltd.", "code": "KSEB", "type": "Electricity" },
    { "name": "kannan devan hills power", "code": "KDHPCPL", "type": "Electricity" },
    { "name": "Lakshadweep Electricity Department", "code": "LED", "type": "Electricity" },
    { "name": "MP Poorv Kshetra Vidyut Vitaran - Jabalpur", "code": "MPPKVVCLPU", "type": "Electricity" },
    { "name": "MP Poorv Kshetra Vidyut Vitaran - Rular", "code": "MPPKVVCLPU", "type": "Electricity" },
    { "name": "Madhya Pradesh Madhya Kshetra Vidyut Vitaran-RURAL", "code": "MPPKVVCLMR", "type": "Electricity" },
    { "name": "Madhya Pradesh Poorv Kshetra Vidyut Vitaran-URBAN", "code": "MPPKVVCL", "type": "Electricity" },
    { "name": "Reliance Energy", "code": "RELIANCE", "type": "Electricity" },
    { "name": "Torrent Power SHIL", "code": "TORRENTSHI", "type": "Electricity" },
    { "name": "Torrent Power Bhivandi", "code": "TORRENTBHI", "type": "Electricity" },
    { "name": "Adani power", "code": "AEML", "type": "Electricity" },
    { "name": "Manipur State Power Distribution Company Limited (Prepaid)", "code": "MSPDCLPR", "type": "Electricity" },
    { "name": "Power & Electricity Department - Mizoram", "code": "MPED", "type": "Electricity" },
    { "name": "Department of Power, Nagaland", "code": "NDOP", "type": "Electricity" },
    { "name": "New Delhi Municipal Council (NDMC) - Electricity", "code": "NDMC", "type": "Electricity" },
    { "name": "NESCO Odisha", "code": "NESCO", "type": "Electricity" },
    { "name": "SOUTHCO Odisha", "code": "SOUTHCO", "type": "Electricity" },
    { "name": "TP central odisha distribution limited", "code": "TPCODL", "type": "Electricity" },
    { "name": "Government of Puducherry Electricity Department", "code": "PGPED", "type": "Electricity" },
    { "name": "TP Ajmer Distribution Ltd", "code": "TPADL", "type": "Electricity" },
    { "name": "Sikkim Power Rural", "code": "SPR", "type": "Electricity" },
    { "name": "Sikkim Power Urban", "code": "SPU", "type": "Electricity" },
    { "name": "Kanpur Electricity Supply Company", "code": "KESCO", "type": "Electricity" },
    { "name": "Torrent Power Dahej", "code": "TORRENTDAH", "type": "Electricity" },
    { "name": "Mahanagar Gas", "code": "MG", "type": "Gas" },
    { "name": "Adani Gas", "code": "AG", "type": "Gas" },
    { "name": "Gujarat Gas", "code": "GG", "type": "Gas" },
    { "name": "Indraprastha Gas", "code": "IG", "type": "Gas" },
    { "name": "Hindustan Petroleum Corporation Ltd", "code": "HPCLGC", "type": "Gas" }
  ]
  